// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.js",
  },
  datasource: {
    // Neon provides POSTGRES_URL, Vercel Postgres provides POSTGRES_PRISMA_URL
    // Set DATABASE_URL to the appropriate value for Prisma to use
    url: process.env["POSTGRES_PRISMA_URL"] || process.env["POSTGRES_URL"] || process.env["DATABASE_URL"] || "",
  },
});
