# /council — Cross-LLM Review of Implementation Plan

<!-- Generated by Council of Models MCP | https://github.com/russellmoss/Council_of_models_mcp -->
<!-- Version: 1.0.0 | Date: 2026-03-26 -->
<!-- This is the generic template. For a project-tailored version, use /setup-council -->

You are running a cross-validation workflow. Your job is to send the implementation plan for this project to GPT and Gemini for adversarial review, then synthesize their feedback for the user.

## Step 1: Find the implementation plan

Look for these files in the project (check in this order):
- Any file matching `*implementation*guide*.md`
- Any file matching `*build*guide*.md`
- Any file matching `*implementation*plan*.md`
- `ARCHITECTURE.md` or `DESIGN.md`
- Any recent `.md` file that looks like a plan or guide

If no plan is found, ask the user: "Which file should I send for cross-LLM review?"

Also read these files if they exist (they provide project context):
- `README.md`
- `package.json`, `tsconfig.json`, `pyproject.toml`, `Cargo.toml`, or equivalent
- Any existing `council-feedback.md` (to see what was already reviewed)

## Step 2: Read all relevant files

Read the implementation plan and all context files found above. You need the full picture before constructing review prompts.

**Important**: Do NOT read `.env`, `node_modules/`, `dist/`, `.git/`, or any file likely to contain secrets.

## Step 3: Investigate the project

Before constructing prompts, silently investigate:
- Read the top-level directory listing and `src/` (or equivalent source folder)
- Identify the tech stack, key dependencies, and project purpose
- Note any existing tests, CI config, or deployment setup

Keep investigation bounded — only read config files and source directory listings, not entire codebases.

## Step 4: Send review prompts

Tell the user: "Sending to OpenAI and Gemini for cross-validation..."

Construct and send these prompts. Send them in parallel where possible using `ask_openai` and `ask_gemini` separately (not `ask_all`) so you can tailor each prompt.

### Prompt A — Send to `ask_openai` (with reasoning_effort: "high")

> You are a senior engineer reviewing an implementation plan.
>
> Context: [Brief description of the project based on what you learned]
>
> Here is the implementation plan:
> [FULL plan text — do not summarize or truncate]
>
> Review for:
> 1. **Missing steps** — Things the plan assumes are done but never tells you to do
> 2. **Wrong paths or commands** — File paths, CLI invocations, or code that won't work
> 3. **Phase ordering problems** — Circular dependencies or steps that should come earlier/later
> 4. **Ambiguous instructions** — Where would someone (or an LLM) get stuck or make a wrong assumption?
> 5. **Missing error handling** — What happens when things fail? Are failure paths covered?
>
> Structure your response as:
> - **CRITICAL** (will break the build or mislead users — must fix before execution)
> - **SHOULD FIX** (won't break things but will cause problems in practice)
> - **DESIGN QUESTIONS** (need the builder's input — include tradeoffs for each option)
>
> For each issue: state what's wrong, where it is (phase/step number), and what the fix should be.

Tell the user: "OpenAI review sent. Waiting for response..."

### Prompt B — Send to `ask_gemini`

> You are a senior engineer challenging an implementation plan from a design perspective.
>
> Context: [Brief description of the project based on what you learned]
>
> Here is the implementation plan:
> [FULL plan text — do not summarize or truncate]
>
> Challenge this plan:
> 1. **Is the approach right?** — Are there simpler or more robust alternatives?
> 2. **What's missing from the architecture?** — Error recovery, edge cases, security, observability?
> 3. **What happens when things break?** — Dependencies update, APIs change, users make mistakes?
> 4. **Business logic assumptions** — Are calculations, data interpretations, and user flows correct?
> 5. **What questions should the builder be asking that they aren't?**
>
> Structure your response as:
> - **CRITICAL** (will break the build or mislead users — must fix before execution)
> - **SHOULD FIX** (won't break things but will cause problems in practice)
> - **DESIGN QUESTIONS** (need the builder's input — include tradeoffs for each option)
>
> For each issue: state what's wrong, where it is, and what the fix should be.

Tell the user: "Gemini review sent. Waiting for response..."

## Step 5: Synthesize feedback

After receiving all responses, tell the user: "Both reviews received. Synthesizing..."

Create a file called `council-feedback.md` in the project root with:

1. **Critical Issues** — Things that are wrong or will break (from any reviewer)
2. **Design Questions** — Open questions the user should answer before proceeding
3. **Suggested Improvements** — Good ideas ranked by impact vs effort
4. **Things to Consider** — Points raised that aren't urgent but worth thinking about
5. **Raw Responses** — The full text from each reviewer, labeled

## Step 6: Present to the user

Show the user:
- A short summary of what the reviewers found (3-5 bullet points)
- The critical issues (if any)
- The design questions that need answers
- Tell them: "Review the full feedback in `council-feedback.md`. Answer the design questions above, then run `/refine` to apply the feedback to the plan."

**Stop here. Do not modify any files other than `council-feedback.md`. Wait for the user.**
