# /refine — Apply Council Feedback to Implementation Plan

<!-- Generated by Council of Models MCP | https://github.com/russellmoss/Council_of_models_mcp -->
<!-- Version: 1.0.0 | Date: 2026-03-26 -->
<!-- This is the generic template. For a project-tailored version, use /setup-council -->

You are applying cross-LLM review feedback to an implementation plan. Read the feedback, triage it, apply what's clear, and ask about what isn't.

## Prerequisites

You need two things to exist before running this command:
1. An implementation plan (the file that was reviewed by `/council`)
2. `council-feedback.md` (created by the `/council` command)

If either is missing, tell the user and stop.

## Step 1: Read everything

Read:
- The implementation plan file
- `council-feedback.md`
- The conversation history (the user's answers to design questions are in the conversation above)

## Step 2: Triage feedback

Sort every piece of feedback into one of three buckets:

### Apply Immediately (no human input needed)
- Missing files or functions that need updating
- Wrong file paths or names
- Incorrect field names, API calls, or commands
- Pattern inconsistencies (align with established patterns)
- Missing NULL/edge case handling
- Missing error handling
- Phase ordering fixes

### Apply Based on User's Answers
- Business logic interpretation choices
- Design tradeoffs where multiple approaches are valid
- Any item flagged as a "Design Question" in the council feedback
- Items where the user gave a clear answer in the conversation

### Note but Don't Apply
- Nice-to-have suggestions that expand scope beyond what was originally planned
- Alternative approaches where the current approach is valid
- Items the user explicitly declined when answering design questions
- Suggestions that would require significant architectural changes

## Step 3: Apply changes

Edit the implementation plan directly:
- Find the exact location of each issue
- Make the change
- If the change affects a validation gate, update the gate too
- If the change affects phase ordering, reorder as needed

## Step 4: Append a Refinement Log

At the bottom of the implementation plan, append:

```
---

## Refinement Log

**Date**: [today's date]
**Source**: council-feedback.md (GPT + Gemini cross-validation)

### Changes Applied
- [List each change: what was wrong, what was fixed, which reviewer caught it]

### Design Decisions
- [List each design question and the user's answer with rationale]

### Noted but Not Applied
- [List items that were acknowledged but deferred, with reason]
```

## Step 5: Self-review

Read the entire updated plan from top to bottom. Verify:
- Phase ordering is still consistent
- No step references a file or function that was renamed/moved
- Validation gates still match what the steps produce
- The refinement log accurately reflects all changes

## Step 6: Report

Tell the user:
- What changed (bullet list)
- What design decisions were made
- What was noted but not applied
- "The plan is updated. You can run `/council` again on the refined plan for another round, or proceed to execution."

**Stop here. Do not begin executing the plan. Wait for the user.**
