// MIRROR — paste from sales-coaching/src/lib/dashboard-api/schemas.ts. CI fails on drift.
// Source: C:\Users\russe\Documents\sales-coaching\src\lib\dashboard-api\schemas.ts
// Last-synced commit hash: 8f7a5da5604668ac8d5bae59ba180e58a8a5eba8
//
// DO NOT EDIT THIS FILE BY HAND. Any change must originate in sales-coaching, then be
// mirrored here byte-for-byte. .github/workflows/schema-mirror-check.yml diffs the two
// and fails on any difference.
/**
 * Canonical Zod schemas for the Dashboard ↔ sales-coaching bridge contract.
 *
 * THIS FILE IS THE SOURCE OF TRUTH. The Dashboard repo
 * (C:\Users\russe\Documents\Dashboard) maintains a byte-for-byte mirror at
 * src/lib/sales-coaching-client/schemas.ts. Dashboard's CI fails on drift
 * — see the Step 5a-UI implementation guide for the mirror enforcement
 * pattern.
 *
 * When changing this file: update Dashboard's mirror in the same PR cycle
 * and bump any consumer's expected schema version. Schemas use `.strict()`
 * so unknown keys are rejected at parse time — explicit allowlist
 * everywhere keeps the contract surface small and auditable.
 *
 * Step 5a-API endpoints + their request/response schemas:
 *
 *   POST   /api/dashboard/users                              CreateUserRequest                 → CreateUserResponse
 *   PATCH  /api/dashboard/users/:id                          UpdateUserRequest                 → UpdateUserResponse
 *   POST   /api/dashboard/users/:id/deactivate               (no body)                         → DeactivateUserResponseOk | (409) DeactivateUserResponseBlocked
 *   POST   /api/dashboard/users/:id/bulk-reassign-pending-evals
 *                                                            BulkReassignRequest               → BulkReassignResponse
 *   PATCH  /api/dashboard/evaluations/:id/reveal-scheduling  RevealSchedulingRequest           → RevealSchedulingResponse
 *   POST   /api/dashboard/evaluations/:id/reveal             ManualRevealRequest               → ManualRevealResponse
 *   PATCH  /api/dashboard/users/me/reveal-policy             UpdateRevealPolicyRequest         → UpdateRevealPolicyResponse
 *   POST   /api/dashboard/content-refinements/:id/resolve    ContentRefinementResolveRequest   → ContentRefinementResolveResponse
 *
 * Author: Step 5a-API Phase 3 (2026-05-08).
 */

import { z } from 'zod';

// ─── Shared primitives ───────────────────────────────────────────────────

// Mirrors RepRole in src/lib/db/types.ts. Migration 036 added 'om'; Thread 2
// will drop 'csa' separately (so for now both coexist on this list).
export const RoleSchema = z.enum(['SGA', 'SGM', 'manager', 'admin', 'csa', 'om']);

// Mirrors RevealPolicy in src/lib/db/types.ts. CHECK on reps.reveal_policy
// allows exactly these three values.
export const RevealPolicySchema = z.enum(['manual', 'auto_delay', 'auto_immediate']);

// PATCH /evaluations/:id/reveal-scheduling vocab. Note: 'reveal_now' and
// 'use_default' are TRANSIENT API VERBS, not persisted into
// evaluations.reveal_override_action (CHECK on the column allows only
// 'hold' | 'custom_delay' | NULL). The route handler intercepts these
// verbs and translates them into either a manualReveal call or a clear-
// override-and-recompute-scheduled_reveal_at action. Council fix S5/DQ4
// adds a structured audit_verb column on evaluation_edit_audit_log so
// the audit trail captures which verb fired.
export const RevealOverrideActionSchema = z.enum([
  'hold',
  'custom_delay',
  'reveal_now',
  'use_default',
]);

export const ContentRefinementResolutionSchema = z.enum(['addressed', 'declined']);

const UuidSchema = z.string().uuid();
const EmailSchema = z
  .string()
  .email()
  .transform((s) => s.toLowerCase().trim());

// ─── POST /api/dashboard/users ───────────────────────────────────────────

export const CreateUserRequest = z
  .object({
    email: EmailSchema,
    full_name: z.string().trim().min(1).max(200),
    role: RoleSchema,
    manager_id: UuidSchema.nullable().optional(),
    slack_user_id: z.string().trim().min(1).max(40).nullable().optional(),
    sfdc_user_id: z.string().trim().min(15).max(18).nullable().optional(),
  })
  .strict();

export const CreateUserResponse = z
  .object({
    rep: z
      .object({
        id: UuidSchema,
        email: z.string(),
        full_name: z.string(),
        role: RoleSchema,
        manager_id: UuidSchema.nullable(),
        is_active: z.boolean(),
        created_at: z.string(),
      })
      .strict(),
  })
  .strict();

// ─── PATCH /api/dashboard/users/:id ──────────────────────────────────────

export const UpdateUserRequest = z
  .object({
    email: EmailSchema.optional(),
    full_name: z.string().trim().min(1).max(200).optional(),
    role: RoleSchema.optional(),
    manager_id: UuidSchema.nullable().optional(),
    slack_user_id: z.string().trim().min(1).max(40).nullable().optional(),
    sfdc_user_id: z.string().trim().min(15).max(18).nullable().optional(),
    reveal_policy: RevealPolicySchema.optional(),
    reveal_delay_minutes: z
      .number()
      .int()
      .min(1)
      .max(10080) // 1 week
      .nullable()
      .optional(),
    reveal_reminder_minutes: z.number().int().min(1).nullable().optional(),
  })
  .strict();

export const UpdateUserResponse = CreateUserResponse;

// ─── POST /api/dashboard/users/:id/deactivate ────────────────────────────
//
// Two response shapes — handler returns 200 with Ok, or 409 with Blocked.

export const DeactivateUserResponseOk = z
  .object({
    rep: z
      .object({
        id: UuidSchema,
        is_active: z.literal(false),
      })
      .strict(),
  })
  .strict();

export const DeactivateUserResponseBlocked = z
  .object({
    blocked_reason: z.enum(['active_direct_reports', 'pending_evaluations']),
    blocking_count: z.number().int().min(1),
    blocking_eval_ids: z.array(UuidSchema).optional(),
    blocking_rep_ids: z.array(UuidSchema).optional(),
  })
  .strict();

// ─── POST /api/dashboard/users/:id/bulk-reassign-pending-evals ───────────

export const BulkReassignRequest = z
  .object({
    new_manager_id: UuidSchema,
  })
  .strict();

export const BulkReassignResponse = z
  .object({
    reassigned_count: z.number().int().min(0),
    reassigned_eval_ids: z.array(UuidSchema),
  })
  .strict();

// ─── PATCH /api/dashboard/evaluations/:id/reveal-scheduling ──────────────
//
// override_action='reveal_now' is intercepted by the route handler and
// routed to manualReveal (POST /reveal's path); the schema accepts it for
// API ergonomics. override_action='use_default' clears the override and
// recomputes scheduled_reveal_at from the evaluation's snapshot policy.

export const RevealSchedulingRequest = z
  .object({
    override_action: RevealOverrideActionSchema,
    override_delay_minutes: z.number().int().min(1).max(10080).optional(),
    expected_edit_version: z.number().int().min(1),
  })
  .strict()
  .refine(
    (v) => v.override_action !== 'custom_delay' || v.override_delay_minutes !== undefined,
    { message: 'override_delay_minutes is required when override_action=custom_delay' },
  );

export const RevealSchedulingResponse = z
  .object({
    evaluation: z
      .object({
        id: UuidSchema,
        edit_version: z.number().int(),
        // Persisted column accepts only 'hold' | 'custom_delay' | NULL —
        // 'reveal_now' / 'use_default' never land here (transient verbs).
        reveal_override_action: z.enum(['hold', 'custom_delay']).nullable(),
        reveal_override_delay_minutes: z.number().int().nullable(),
        scheduled_reveal_at: z.string().nullable(),
      })
      .strict(),
  })
  .strict();

// ─── POST /api/dashboard/evaluations/:id/reveal ──────────────────────────

export const ManualRevealRequest = z
  .object({
    expected_edit_version: z.number().int().min(1),
  })
  .strict();

export const ManualRevealResponse = z
  .object({
    evaluation: z
      .object({
        id: UuidSchema,
        edit_version: z.number().int(),
        status: z.literal('revealed'),
        revealed_at: z.string(),
      })
      .strict(),
  })
  .strict();

// ─── PATCH /api/dashboard/users/me/reveal-policy ─────────────────────────

export const UpdateRevealPolicyRequest = z
  .object({
    policy: RevealPolicySchema,
    delay_minutes: z.number().int().min(1).max(10080).nullable().optional(),
    reminder_minutes: z.number().int().min(1).nullable().optional(),
  })
  .strict()
  .superRefine((v, ctx) => {
    if (
      v.policy === 'auto_delay' &&
      (v.delay_minutes === null || v.delay_minutes === undefined)
    ) {
      ctx.addIssue({
        code: 'custom',
        path: ['delay_minutes'],
        message: 'delay_minutes required when policy=auto_delay',
      });
    }
    if (
      v.reminder_minutes != null &&
      v.delay_minutes != null &&
      v.reminder_minutes >= v.delay_minutes
    ) {
      ctx.addIssue({
        code: 'custom',
        path: ['reminder_minutes'],
        message: 'reminder_minutes must be less than delay_minutes',
      });
    }
  });

export const UpdateRevealPolicyResponse = z
  .object({
    rep: z
      .object({
        id: UuidSchema,
        reveal_policy: RevealPolicySchema,
        reveal_delay_minutes: z.number().int().nullable(),
        reveal_reminder_minutes: z.number().int().nullable(),
      })
      .strict(),
  })
  .strict();

// ─── POST /api/dashboard/content-refinements/:id/resolve ─────────────────

export const ContentRefinementResolveRequest = z
  .object({
    resolution: ContentRefinementResolutionSchema,
    resolution_notes: z.string().trim().min(1).max(2000).optional(),
  })
  .strict()
  .superRefine((v, ctx) => {
    if (v.resolution === 'declined' && !v.resolution_notes) {
      ctx.addIssue({
        code: 'custom',
        path: ['resolution_notes'],
        message: 'resolution_notes required when resolution=declined',
      });
    }
  });

export const ContentRefinementResolveResponse = z
  .object({
    request: z
      .object({
        id: UuidSchema,
        status: ContentRefinementResolutionSchema,
        resolved_by: UuidSchema,
        resolved_at: z.string(),
        resolution_notes: z.string().nullable(),
      })
      .strict(),
  })
  .strict();

// ─── Generic error envelope ──────────────────────────────────────────────
//
// Mirrors the existing { ok: false, error } shape the server.ts errorHandler
// emits. Dashboard parses this for ALL non-2xx responses.

export const ErrorResponseSchema = z
  .object({
    ok: z.literal(false).optional(),
    error: z.string(),
    message: z.string().optional(),
    // Auth-failure detail (DashboardRoleError → 403)
    actual_role: z.string().optional(),
    allowed_roles: z.array(z.string()).optional(),
    // OCC conflict detail (EvaluationConflictError → 409)
    // (no extra fields beyond `message`)
    // Deactivate-blocked detail (409)
    blocked_reason: z.string().optional(),
    blocking_count: z.number().optional(),
    blocking_eval_ids: z.array(UuidSchema).optional(),
    blocking_rep_ids: z.array(UuidSchema).optional(),
  })
  .strict();

// ─── Inferred TypeScript types — exported for handler convenience ────────

export type CreateUserRequestT = z.infer<typeof CreateUserRequest>;
export type CreateUserResponseT = z.infer<typeof CreateUserResponse>;
export type UpdateUserRequestT = z.infer<typeof UpdateUserRequest>;
export type UpdateUserResponseT = z.infer<typeof UpdateUserResponse>;
export type DeactivateUserResponseOkT = z.infer<typeof DeactivateUserResponseOk>;
export type DeactivateUserResponseBlockedT = z.infer<typeof DeactivateUserResponseBlocked>;
export type BulkReassignRequestT = z.infer<typeof BulkReassignRequest>;
export type BulkReassignResponseT = z.infer<typeof BulkReassignResponse>;
export type RevealSchedulingRequestT = z.infer<typeof RevealSchedulingRequest>;
export type RevealSchedulingResponseT = z.infer<typeof RevealSchedulingResponse>;
export type ManualRevealRequestT = z.infer<typeof ManualRevealRequest>;
export type ManualRevealResponseT = z.infer<typeof ManualRevealResponse>;
export type UpdateRevealPolicyRequestT = z.infer<typeof UpdateRevealPolicyRequest>;
export type UpdateRevealPolicyResponseT = z.infer<typeof UpdateRevealPolicyResponse>;
export type ContentRefinementResolveRequestT = z.infer<typeof ContentRefinementResolveRequest>;
export type ContentRefinementResolveResponseT = z.infer<typeof ContentRefinementResolveResponse>;
export type ErrorResponseT = z.infer<typeof ErrorResponseSchema>;
export type RoleT = z.infer<typeof RoleSchema>;
export type RevealPolicyT = z.infer<typeof RevealPolicySchema>;
