const fs = require("fs");
const p1 = [
"# Data Verifier Findings: SQO Calculator + Realization Forecast + Scenario Runner",
"**Date:** 2026-03-25",
"**Analyst:** Data Verifier agent (Claude Sonnet 4.6)",
"",
"---",
"",
"## Query 1: Component A Pipeline for Upcoming Quarters",
"",
"Filter: SQO_raw=Yes, is_sqo_unique=1, StageName IN (Negotiating, Signed), anticipated_date >= CURRENT_DATE()",
"",
"| target_quarter | deal_count | aum_m | neg_count | signed_count |",
"|---|---|---|---|---|",
"| Q1 2026 | 2 | 100.2 | 2 | 0 |",
"| Q2 2026 | 29 | 2527.4 | 25 | 4 |",
"| Q3 2026 | 2 | 364.5 | 2 | 0 |",
"",
"Notes:",
"- Q1 2026: 2 deals still open. Q1 ends 2026-03-31. Very likely to slip to Q2.",
"- Q2 2026: 29 deals, 2.527B gross Component A AUM (25 Neg, 4 Signed). Primary forecast target.",
"- Q3 2026: only 2 deals (364.5M). Too thin for reliable realization banding.",
"- No Q4 2026+ deals in Neg/Signed with anticipated dates.",
"- Flag: query uses >= CURRENT_DATE() so Q1 2026 in-progress deals ARE included.",
"",
"---",
"",
"## Query 2: Mean Joined AUM by Trailing Window",
"",
"Filter: SQO_raw=Yes, is_primary_opp_record=1, StageName=Joined, AUM > 0",
"",
"| window | n (joined deals) | mean_aum_m |",
"|---|---|---|",
"| 180d | 13 | 49.8 |",
"| 1yr | 45 | 97.7 |",
"| 2yr | 85 | 73.9 |",
"| all-time | 112 | 65.4 |",
"",
"Spec verification: spec referenced ~65.5M all-time, ~97.3M at 1yr.",
"Actuals: 65.4M all-time, 97.7M 1yr. CONFIRMED accurate.",
"",
"DATA QUALITY FLAG - 180d window n=13: BELOW 30-DEAL THRESHOLD.",
"Warning WILL trigger for 180d window. Mean of 49.8M from 13 deals is unreliable.",
"",
"1yr vs all-time divergence: 97.7M vs 65.4M (49% higher). Reflects large 2025 deals.",
"Surface this variance prominently in the SQO calculator UI."
].join("\n");
fs.writeFileSync("C:/Users/russe/documents/dashboard/data-verifier-findings.md", p1, "utf8");
console.log("Part 1 written");
