const fs = require("fs");
const p2 = [
"",
"---",
"",
"## Query 3: Component B Surprise AUM -- CRITICAL FINDING",
"",
"Expected from spec: trailing 4Q average ~398M with meaningful surprise AUM each quarter.",
"",
"| join_quarter | total_joined | total_aum_m | comp_a_count | comp_a_aum_m | surprise_aum_m |",
"|---|---|---|---|---|---|",
"| Q1 2025 | 12 | 462.9 | 12 | 462.9 | 0.0 |",
"| Q2 2025 | 11 | 578.0 | 11 | 578.0 | 0.0 |",
"| Q3 2025 | 14 | 765.0 | 13 | 744.0 | 21.0 |",
"| Q4 2025 | 17 | 1318.2 | 17 | 1318.2 | 0.0 |",
"",
"RESULT: Component B (surprise AUM) is effectively ZERO for all 2025 quarters.",
"This directly contradicts the backtest finding of ~398M trailing 4Q average.",
"",
"### Root Cause: Earliest_Anticipated_Start_Date__c Is Overwritten After Join",
"",
"Investigation on joined deals (2024+, n=75 with anticipated dates set):",
"  - Exact match (anticipated == actual join date): 55 deals (73.3%)",
"  - Different values (true pre-join forecast date): 20 deals (26.7%)",
"",
"Salesforce reps update Earliest_Anticipated_Start_Date__c to match advisor_join_date__c",
"after the deal closes. vw_funnel_master shows the post-join-updated value, NOT the",
"original forecast value. The backtest restored pre-join dates using OpportunityFieldHistory",
"PIT reconstruction -- that is NOT available in the current view.",
"",
"Anticipated date population rate by stage (all time):",
"  - Negotiating:  100.0% (31/31)",
"  - Signed:       100.0% (4/4)",
"  - Joined:        65.8% (75/114) -- 73.3% of those match the actual join date",
"  - Closed Lost:   22.1% (156/707)",
"",
"### Implementation Options for Component B",
"",
"OPTION 1 (RECOMMENDED for v1):",
"  Hard-code 398M from the PIT backtest as SURPRISE_BASELINE_AUM constant.",
"  Add a cell note in the Realization Sheet explaining it derives from the backtest.",
"  Update quarterly. Implement as a constant in buildRealizationValues().",
"",
"OPTION 2 (long-term correct, requires view change):",
"  Build a new BigQuery view using OpportunityFieldHistory to reconstruct pre-join",
"  anticipated dates. Requires new view + PIT reconstruction SQL.",
"  FLAG AS VIEW CHANGE REQUIREMENT if this option is chosen.",
"",
"OPTION 3 (NOT viable):",
"  total_joined_aum - component_a_aum from current view gives ~0 as shown above."
].join("\n");
fs.appendFileSync("C:/Users/russe/documents/dashboard/data-verifier-findings.md", p2, "utf8");
console.log("Part 2 appended");
